# Generated by Django 5.1.5 on 2025-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default="Описание не указано", null=False),
        ),
    ]
