# Generated by Django 5.1.5 on 2025-02-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
